name: geo_valid_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- State Management & Routing ---
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0

  # --- UI & Fonts ---
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # --- Backend & Auth ---
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1
  http: ^1.2.0

  # --- Hardware & Media ---
  image_picker: ^1.0.7
  camera: ^0.10.5
  permission_handler: ^11.3.0
  geolocator: ^10.1.0
  url_launcher: ^6.3.0

  # --- Maps ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # --- Storage ---
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # --- Formatting & Localization ---
  # [PERBAIKAN: Ikuti versi yang diminta SDK]
  intl: ^0.20.2

  flutter_localizations:
    sdk: flutter

  # --- Caching & Utils ---
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  flutter_markdown: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- Testing Dependencies ---
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    # - assets/patahan_aktif.geojson